name: On Branch
on: workflow_dispatch
  # push:
  #   branches:
  #     - main
  #     - dev
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        run: echo "welcome to push trigger"
